/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    NavMenuItem: typeof import('./src/components/NavMenuItem.vue')['default']
    NCarousel: typeof import('./src/components/nCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
